name: Main

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  check_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
        dependency-version: [ 'prefer-stable' ]
    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ github.event.repository.full_name }}-php-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, json, dom, curl, libxml, zip
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        id: composer-install
        if: ${{ strategy.job-total == 1 }}
        run: composer install --prefer-dist --no-interaction

      - name: Install and update dependencies to given versions
        id: composer-update
        if: ${{ strategy.job-total > 1 }}
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Run GrumPHP
        run: php vendor/bin/grumphp run --tasks=phpstan,securitychecker_composeraudit

      - name: Execute tests
        run: composer run test
